/**
 * Original prompt pack for Quip Game. Two tiers: 'clean' is safe for any table, 'cheeky' is adult
 * humour (innuendo and embarrassment, never slurs). The host enables cheeky prompts in the lobby.
 * Prompts are written as the start of a sentence or a short question the player completes.
 */
export type PromptTier = 'clean' | 'cheeky';

export interface Prompt {
  text: string;
  tier: PromptTier;
}

const clean = (text: string): Prompt => ({ text, tier: 'clean' });
const cheeky = (text: string): Prompt => ({ text, tier: 'cheeky' });

export const PROMPTS: readonly Prompt[] = [
  clean("The worst thing to hear from your dentist"),
  clean("A rejected name for a new breakfast cereal"),
  clean("The least inspiring motivational poster"),
  clean("Something you should never say at a job interview"),
  clean("A terrible name for a pet goldfish"),
  clean("The real reason the dinosaurs went extinct"),
  clean("What cats are actually plotting"),
  clean("The worst superpower"),
  clean("A bad slogan for a bank"),
  clean("The least popular flavour of ice cream"),
  clean("A surprising thing to find in your grandma's attic"),
  clean("The worst thing to say when meeting your partner's parents"),
  clean("A new holiday nobody asked for"),
  clean("The secret ingredient in school cafeteria food"),
  clean("The worst name for a cruise ship"),
  clean("Something you should never microwave"),
  clean("A rejected title for a romance novel"),
  clean("The first rule of a very bad club"),
  clean("What your dog would say if it could talk for five seconds"),
  clean("A terrible theme for a wedding"),
  clean("The worst dish to bring to a potluck"),
  clean("A bad name for a dating app"),
  clean("The most disappointing thing to unwrap on your birthday"),
  clean("An unusual thing to be famous for"),
  clean("The worst sound to hear at 3 a.m."),
  clean("A new Olympic event"),
  clean("The least useful app on your phone"),
  clean("Something you'd never expect a pilot to announce"),
  clean("A rejected flavour of toothpaste"),
  clean("The worst thing to find in your sandwich"),
  clean("A bad name for a superhero"),
  clean("The Wi-Fi password at a haunted house"),
  clean("The worst thing to say to a police officer"),
  clean("A new word that should be in the dictionary"),
  clean("The real reason the chicken crossed the road"),
  clean("A terrible name for a yoga studio"),
  clean("Something on a supervillain's to-do list"),
  clean("The worst advice from a fortune cookie"),
  clean("A rejected Olympic mascot"),
  clean("The least scary Halloween costume"),
  clean("Something you should never search for at work"),
  clean("A bad name for a perfume"),
  clean("The most annoying thing a robot could say"),
  clean("What aliens think humans do for fun"),
  clean("The worst thing to yell at a golf tournament"),
  clean("A new rule for the gym"),
  clean("A terrible name for a boat"),
  clean("Something you'd never hear a tour guide say"),
  clean("The worst way to start a speech"),
  clean("A bad excuse for being late"),
  clean("The worst ride at a theme park"),
  clean("A rejected name for a paint colour"),
  clean("Something that would ruin a camping trip"),
  clean("What the Moon really thinks of the Earth"),
  clean("A terrible name for a hair salon"),
  clean("The worst thing to say at a funeral"),
  clean("A new car feature nobody wants"),
  clean("The most useless kitchen gadget"),
  clean("The worst thing to say to your barber"),
  clean("A rejected name for a sports team"),
  clean("Something to put in a time capsule just to confuse the future"),
  clean("A strange thing to collect"),
  clean("The worst title for a cookbook"),
  clean("The last thing the last dinosaur said"),
  clean("The worst thing to whisper in a library"),
  clean("A terrible name for a coffee shop"),
  clean("The least impressive world record"),
  clean("Something you'd never see on a restaurant menu"),
  clean("A bad name for a hotel"),
  clean("What your fridge would say about you"),
  clean("The worst slogan for a toothbrush"),
  clean("A crisp flavour that should not exist"),
  clean("The worst thing to say to your teacher"),
  clean("A rejected Disney princess"),
  clean("Something at the bottom of a very deep lake"),
  clean("A terrible name for a band"),
  clean("The worst thing to happen on live TV"),
  clean("A sign you're staying in a bad hotel"),
  clean("The worst name for a laundromat"),
  clean("What pigeons gossip about"),
  clean("A bad reason to call in sick"),
  clean("The worst question to ask a magician"),
  clean("A rejected name for a chocolate bar"),
  clean("The weirdest thing to see on a billboard"),
  clean("A terrible theme for a kid's birthday party"),
  clean("The worst tagline for a horror movie"),
  clean("The least popular ride at the fair"),
  clean("Something that would make a teacher's job harder"),
  clean("A bad name for a bakery"),
  clean("What squirrels are saving up for"),
  clean("The worst thing to be allergic to"),
  clean("A rejected name for a space mission"),
  clean("The worst thing to hear your GPS say"),
  clean("A bad thing to write in a wedding card"),
  clean("A strange thing to find in a vending machine"),
  clean("A terrible name for a gym"),
  clean("The worst thing to say on a first date"),
  clean("A sign your neighbour is a wizard"),
  clean("The least convincing excuse for not doing homework"),
  clean("A new rule for airplanes"),
  clean("The worst name for a plumbing business"),
  clean("Something you shouldn't say to a chef"),
  clean("A rejected name for a crayon colour"),
  clean("The worst thing to hear from your mechanic"),
  clean("A terrible name for a pizza place"),
  clean("What a snowman fears most"),
  clean("The worst present for a baby"),
  clean("A reality TV show that would get cancelled instantly"),
  clean("Something you'd never see in a museum"),
  clean("The worst thing to bring on a hike"),
  clean("A terrible name for a candle scent"),
  clean("What the ocean would complain about"),
  clean("The worst thing to say to a flight attendant"),
  clean("A bad name for a mattress company"),
  clean("The worst way to propose"),
  clean("A rejected name for a games console"),
  clean("A strange hobby for a grandparent"),
  clean("The worst thing a waiter could say"),
  clean("The least useful phrase to teach a parrot"),
  clean("A bad name for a racehorse"),
  clean("The worst thing to find in a hotel pool"),
  clean("A terrible name for a lipstick shade"),
  clean("Something you'd never put on a pizza"),
  clean("What your socks get up to while you sleep"),
  clean("A rejected name for a theme park"),
  clean("The worst motivational speech of all time"),
  clean("A bad name for a lawnmower brand"),
  clean("Something you don't want to hear from your surgeon"),
  clean("A terrible name for an energy drink"),
  clean("What the Loch Ness Monster does on weekends"),
  clean("A new school subject"),
  clean("The worst thing to say to a bus driver"),
  clean("A rejected title for a movie sequel"),
  clean("A terrible thing to find in a cereal box"),
  clean("The worst name for a furniture store"),
  clean("Something you'd never shout at a concert"),
  clean("The real reason Monday exists"),
  clean("A bad name for a detective agency"),
  clean("The worst thing to sell at a lemonade stand"),
  clean("The one thing a goldfish remembers"),
  clean("A terrible name for a toy"),
  clean("The worst thing to say to a lifeguard"),
  clean("An emoji we desperately need"),
  clean("A strange thing to see a cow doing"),
  clean("The worst thing to hear from your landlord"),
  clean("A bad name for a phone company"),
  clean("Something you'd never find in a toolbox"),
  clean("The worst thing to put on a CV"),
  clean("A terrible name for a pet shop"),
  clean("The worst way to be woken up"),
  clean("A rejected name for a hurricane"),
  clean("The worst thing to shout at a surprise party"),
  clean("A bad name for a shampoo"),
  clean("The most boring museum exhibit"),
  clean("Something you shouldn't wear to the beach"),
  clean("A terrible thing to carve into a pumpkin"),
  clean("The least useful gadget for an astronaut"),
  clean("A bad name for a taxi company"),
  clean("The worst thing to find in your shoe"),
  clean("A rejected name for a new planet"),
  clean("What your houseplants say when you leave the room"),
  clean("The worst thing to hear at the top of a rollercoaster"),
  clean("A terrible name for a tea brand"),
  clean("Something you'd never do at a wedding"),
  clean("The worst thing to say to Santa"),
  clean("A new reason to cancel plans"),
  clean("The worst name for a bicycle"),
  clean("A sign your cat is a secret agent"),
  clean("A terrible idea for a themed restaurant"),
  clean("The least popular animal at the zoo"),
  clean("The worst thing to bring to a picnic"),
  clean("A bad name for a fitness class"),
  clean("Something you'd never hear a weather forecaster say"),
  clean("The worst thing to find in a treasure chest"),
  clean("A rejected name for a pasta shape"),
  clean("What ghosts do on their day off"),
  clean("The worst slogan for a dentist"),
  clean("A terrible thing to say to a crying baby"),
  clean("A new sport for people who hate sport"),
  clean("The worst thing to see in your rear-view mirror"),
  clean("A bad name for a knitting club"),
  clean("The worst thing to say to a museum guard"),
  clean("A rejected name for a cat café"),
  clean("The least popular job at the circus"),
  clean("Something you'd never find in a first-aid kit"),
  clean("A terrible name for a sandwich"),
  clean("The worst way to end a phone call"),
  clean("A bad name for a camping shop"),
  clean("What snails think about traffic"),
  clean("The worst thing to hear from a tattoo artist"),
  clean("A terrible name for a water park"),
  clean("The worst thing to sell door to door"),
  clean("A strange thing to be world champion of"),
  clean("The worst thing to say to a bride"),
  clean("A bad name for a children's TV show"),
  clean("A sign you've hired a bad babysitter"),
  clean("The worst thing to find written on a birthday cake"),
  clean("A rejected name for a yoga pose"),
  clean("What the Tooth Fairy does with all those teeth"),
  clean("The worst thing to say to a mime"),
  clean("A terrible name for a ski resort"),
  clean("The most useless superhero gadget"),
  clean("A bad name for a brand of socks"),
  clean("Something a pirate would never say"),
  clean("The worst reply to \"I love you\""),
  clean("A rejected board game"),
  clean("The worst thing to hear from your optician"),
  clean("A bad name for a cheese"),
  clean("Something you'd find in a dragon's junk drawer"),
  clean("The worst thing to put on toast"),
  clean("A terrible name for a smartwatch"),
  clean("The least exciting thing to win in a raffle"),
  clean("A bad name for a brand of glue"),
  clean("What a traffic cone dreams about"),
  clean("The worst thing to say to a vampire"),
  clean("A rejected name for a dog breed"),
  clean("The worst song to play at a baby shower"),
  clean("A terrible name for a submarine"),
  clean("Something a wizard regrets buying"),
  clean("The worst thing to hear from your personal trainer"),
  clean("A bad name for a brand of umbrella"),
  clean("A surprising thing to learn about penguins"),
  clean("The worst thing to find in your pocket"),
  clean("A rejected name for a comet"),
  clean("What Bigfoot is hiding from"),
  clean("The worst thing to say to a judge"),
  clean("A terrible name for a chewing gum"),
  cheeky("The worst thing to say right after a kiss"),
  cheeky("A terrible name for an adult shop"),
  cheeky("The worst text to send to the wrong person"),
  cheeky("A bad name for a dating profile"),
  cheeky("Something you don't want to hear from your doctor during a physical"),
  cheeky("The worst thing to find in your partner's search history"),
  cheeky("A rejected pickup line"),
  cheeky("The worst thing to say in bed"),
  cheeky("A bad name for a strip club"),
  cheeky("The least sexy thing to whisper"),
  cheeky("The worst thing to hear your parents say through the wall"),
  cheeky("The most embarrassing thing to be caught doing by your boss"),
  cheeky("A terrible name for a beer"),
  cheeky("The worst thing to happen during a hot date"),
  cheeky("A bad excuse for coming home at 4 a.m."),
  cheeky("The worst place to get a tattoo"),
  cheeky("Something you shouldn't say to your in-laws"),
  cheeky("A terrible name for a hangover cure"),
  cheeky("The worst thing to see written on a bathroom wall"),
  cheeky("A bad name for a brand of underwear"),
  cheeky("The worst thing to say during a massage"),
  cheeky("The most embarrassing ringtone to go off in church"),
  cheeky("A terrible tattoo to get on a dare"),
  cheeky("The worst thing to say to the bouncer"),
  cheeky("A rejected name for a cocktail"),
  cheeky("The worst thing to find in the hotel nightstand drawer"),
  cheeky("A bad name for a hot tub company"),
  cheeky("The worst thing to hear from a stranger at the urinal"),
  cheeky("A terrible wedding night surprise"),
  cheeky("The worst thing to say to your ex at a party"),
  cheeky("The most awkward thing to happen in an elevator"),
  cheeky("A bad name for a laxative"),
  cheeky("The worst thing to find in your hotel bed"),
  cheeky("A terrible nickname your partner could give you"),
  cheeky("The worst thing to say to a nudist"),
  cheeky("The most embarrassing thing to drop in front of your crush"),
  cheeky("The worst thing to yell during a wedding ceremony"),
  cheeky("The worst thing to discover about your roommate"),
  cheeky("A terrible thing to say to a fortune teller"),
  cheeky("The worst thing to hear during a prostate exam"),
  cheeky("The most embarrassing thing to search for in front of your mum"),
  cheeky("A bad name for a waxing salon"),
  cheeky("The worst thing to say to your partner's ex"),
  cheeky("The worst thing to put on a dating profile"),
  cheeky("The most awkward moment at a family reunion"),
  cheeky("A terrible thing to shout in a crowded sauna"),
  cheeky("The worst thing to say to a bartender at closing time"),
  cheeky("A bad name for a stag party planner"),
  cheeky("The worst thing to happen on a nudist beach"),
  cheeky("The worst thing to hear from your taxi driver"),
  cheeky("A terrible thing to find out on your honeymoon"),
  cheeky("The worst thing to say to a pregnant woman"),
  cheeky("A bad name for a brand of condoms"),
  cheeky("The worst thing to see on your partner's phone"),
  cheeky("The most embarrassing thing to happen at the gym"),
  cheeky("A terrible slogan for a plastic surgeon"),
  cheeky("The worst thing to say at a hen party"),
  cheeky("The worst thing to find in the office fridge"),
  cheeky("A bad name for a massage parlour"),
  cheeky("The worst thing to admit on a first date"),
  cheeky("The most embarrassing song to be caught singing in the shower"),
  cheeky("A terrible thing to write on a toilet door"),
  cheeky("The worst thing to hear from a hairdresser mid-haircut"),
  cheeky("The worst secret to reveal at Christmas dinner"),
  cheeky("A bad name for a nightclub"),
  cheeky("The worst thing to do at a strip club"),
  cheeky("The worst way to describe your rash to a doctor"),
  cheeky("A terrible opening line for a breakup text"),
  cheeky("The worst possible answer to \"what are you thinking about?\""),
  cheeky("The worst thing to find in your teenager's room"),
  cheeky("A bad name for an energy drink for adults only"),
  cheeky("The worst sound to hear from the bathroom at a party"),
  cheeky("The most embarrassing nickname from your childhood"),
  cheeky("A terrible thing to say when the lights come back on"),
  cheeky("The worst thing to hear at a nudist colony buffet"),
  cheeky("The worst thing to whisper to a stranger on a plane"),
  cheeky("A bad name for a lingerie store"),
  cheeky("The worst thing to find in your drink"),
  cheeky("The worst thing to say to your dentist while their fingers are in your mouth"),
  cheeky("A terrible safe word"),
  cheeky("The worst thing to confess in a wedding toast"),
  cheeky("The most embarrassing thing to be allergic to"),
  cheeky("A bad name for a dating app for seniors"),
  cheeky("The worst thing to hear from your partner's best friend"),
  cheeky("The worst thing to see on a webcam during a work call"),
  cheeky("A terrible thing to shout at a life-drawing class"),
  cheeky("The worst thing to find in a motorway service station vending machine"),
  cheeky("The worst thing to hear from your blind date's mother"),
  cheeky("A bad name for a tattoo parlour"),
  cheeky("The worst thing to say when you walk in on someone"),
  cheeky("The worst thing to order on a first date at a fancy restaurant"),
  cheeky("A terrible excuse for a hickey"),
  cheeky("The worst thing to find in your partner's gym bag"),
  cheeky("The worst thing to hear from a dating app match in the first minute"),
  cheeky("The worst thing to say to your boss at the office party after three drinks"),
  cheeky("The most embarrassing thing to happen on a video call"),
  cheeky("A terrible name for a couples' retreat"),
  cheeky("The worst thing to find written in your yearbook"),
  cheeky("A bad name for a brand of edible underwear"),
  cheeky("The worst thing to say to a stranger in a hot tub"),
  cheeky("The least romantic place to say \"I love you\" for the first time"),
  cheeky("The worst thing to hear from the person you just went home with"),
  cheeky("A terrible thing to say to your partner's grandmother"),
  cheeky("The worst way to find out you're on a date"),
  cheeky("A bad name for a brand of body spray"),
  cheeky("The worst thing to say when the waiter asks if you'd like dessert"),
  cheeky("The most embarrassing thing to leave in a rental car"),
  cheeky("A terrible name for a honeymoon suite"),
];

/** Used when a player runs out of time; chosen at random so the matchup still works. */
export const FALLBACK_ANSWERS: readonly string[] = [
  'I got nothing',
  '...',
  '[ran out of time]',
  'insert joke here',
  'my dog ate my answer',
  'pass',
  'the sound of silence',
  'ask me again later',
  'a very long pause',
  'no comment',
];
