/** English word list: concrete, drawable things. Deduplicated at import time by ./index.ts. */
export const EN_WORDS: string[] = [
  // animals
  'cat', 'dog', 'elephant', 'giraffe', 'lion', 'tiger', 'zebra', 'monkey', 'gorilla', 'kangaroo', 'koala', 'panda',
  'bear', 'polar bear', 'wolf', 'fox', 'rabbit', 'hamster', 'mouse', 'rat', 'squirrel', 'hedgehog', 'raccoon',
  'deer', 'moose', 'horse', 'donkey', 'cow', 'bull', 'pig', 'sheep', 'goat', 'llama', 'camel', 'rhino', 'hippo',
  'crocodile', 'alligator', 'turtle', 'tortoise', 'snake', 'cobra', 'lizard', 'chameleon', 'frog', 'toad',
  'salamander', 'dinosaur', 't-rex', 'dragon', 'unicorn', 'mermaid', 'penguin', 'owl', 'eagle', 'parrot',
  'flamingo', 'peacock', 'swan', 'duck', 'goose', 'chicken', 'rooster', 'turkey', 'ostrich', 'pigeon', 'crow',
  'hummingbird', 'woodpecker', 'bat', 'butterfly', 'caterpillar', 'bee', 'wasp', 'ant', 'spider', 'scorpion',
  'ladybug', 'dragonfly', 'mosquito', 'fly', 'snail', 'worm', 'grasshopper', 'beetle', 'firefly', 'shark',
  'whale', 'dolphin', 'octopus', 'squid', 'jellyfish', 'starfish', 'seahorse', 'crab', 'lobster', 'shrimp',
  'clownfish', 'goldfish', 'pufferfish', 'swordfish', 'eel', 'seal', 'walrus', 'otter', 'beaver', 'sloth',
  'armadillo', 'porcupine', 'skunk', 'meerkat', 'chipmunk', 'bison', 'reindeer', 'cheetah', 'leopard', 'hyena',
  'baboon', 'orangutan', 'anteater', 'platypus', 'kiwi', 'puppy', 'kitten', 'nest', 'beehive', 'web',
  // food & drink
  'pizza', 'hamburger', 'hot dog', 'french fries', 'sandwich', 'taco', 'burrito', 'sushi', 'spaghetti',
  'noodles', 'ramen', 'dumpling', 'pancake', 'waffle', 'toast', 'bread', 'baguette', 'croissant', 'pretzel',
  'bagel', 'donut', 'cupcake', 'cake', 'birthday cake', 'pie', 'cookie', 'brownie', 'ice cream', 'popsicle',
  'lollipop', 'candy', 'candy cane', 'chocolate', 'gingerbread man', 'popcorn', 'chips', 'cheese', 'egg',
  'fried egg', 'bacon', 'sausage', 'steak', 'chicken leg', 'fish and chips', 'soup', 'salad', 'rice',
  'cereal', 'milk', 'coffee', 'tea', 'juice', 'lemonade', 'soda', 'water bottle', 'beer', 'wine', 'milkshake',
  'apple', 'banana', 'orange', 'lemon', 'lime', 'grapes', 'strawberry', 'cherry', 'watermelon', 'pineapple',
  'peach', 'pear', 'plum', 'kiwi fruit', 'mango', 'coconut', 'avocado', 'blueberry', 'raspberry', 'melon',
  'carrot', 'broccoli', 'corn', 'tomato', 'potato', 'onion', 'garlic', 'pumpkin', 'cucumber', 'pepper',
  'chili pepper', 'mushroom', 'peas', 'lettuce', 'eggplant', 'pickle', 'olive', 'peanut', 'honey', 'jam',
  'butter', 'ketchup', 'mustard', 'salt', 'sugar', 'lunchbox', 'picnic', 'barbecue', 'kebab', 'meatball',
  'lasagna', 'omelette', 'pudding', 'jelly', 'marshmallow', 'cotton candy', 'nachos', 'quesadilla', 'tofu',
  // household objects
  'chair', 'table', 'sofa', 'bed', 'pillow', 'blanket', 'lamp', 'candle', 'clock', 'alarm clock', 'mirror',
  'window', 'door', 'key', 'lock', 'doorbell', 'stairs', 'ladder', 'bookshelf', 'book', 'newspaper', 'magazine',
  'television', 'remote control', 'radio', 'speaker', 'headphones', 'microphone', 'camera', 'telephone',
  'smartphone', 'laptop', 'computer', 'keyboard', 'mouse pad', 'printer', 'light bulb', 'flashlight',
  'battery', 'plug', 'fan', 'air conditioner', 'heater', 'fireplace', 'chimney', 'vacuum cleaner', 'broom',
  'mop', 'bucket', 'sponge', 'soap', 'shampoo', 'toothbrush', 'toothpaste', 'towel', 'bathtub', 'shower',
  'toilet', 'toilet paper', 'sink', 'faucet', 'comb', 'hairbrush', 'hair dryer', 'razor', 'scissors',
  'needle', 'thread', 'button', 'zipper', 'safety pin', 'iron', 'washing machine', 'dryer', 'hanger',
  'wardrobe', 'drawer', 'suitcase', 'backpack', 'handbag', 'wallet', 'coin', 'money', 'piggy bank', 'gift',
  'balloon', 'party hat', 'confetti', 'trophy', 'medal', 'ribbon', 'bow', 'calendar', 'map', 'globe',
  'compass', 'binoculars', 'magnifying glass', 'telescope', 'microscope', 'thermometer', 'bandage',
  'first aid kit', 'pill', 'syringe', 'wheelchair', 'crutches', 'glasses', 'sunglasses', 'umbrella', 'cane',
  'kettle', 'teapot', 'cup', 'mug', 'glass', 'bottle', 'can', 'jar', 'plate', 'bowl', 'fork', 'knife',
  'spoon', 'chopsticks', 'frying pan', 'pot', 'oven', 'microwave', 'toaster', 'blender', 'refrigerator',
  'freezer', 'stove', 'grill', 'apron', 'oven mitt', 'cutting board', 'rolling pin', 'whisk', 'grater',
  'trash can', 'recycling bin', 'paper bag', 'box', 'tape', 'glue', 'stapler', 'paper clip', 'pencil', 'pen',
  'marker', 'crayon', 'eraser', 'ruler', 'notebook', 'envelope', 'stamp', 'letter', 'postcard', 'scroll',
  'paintbrush', 'palette', 'easel', 'canvas', 'picture frame', 'poster', 'sticker', 'puzzle', 'dice',
  'playing cards', 'chess', 'checkers', 'domino', 'teddy bear', 'doll', 'yo-yo', 'kite', 'marbles', 'lego',
  'robot', 'rocking horse', 'slingshot', 'water gun', 'frisbee', 'boomerang', 'hula hoop', 'jump rope',
  'swing', 'slide', 'seesaw', 'sandbox', 'sandcastle', 'treehouse', 'tent', 'sleeping bag', 'campfire',
  'lantern', 'hammock', 'fishing rod', 'hook', 'net', 'anchor', 'life jacket', 'surfboard', 'snorkel',
  'goggles', 'flippers', 'skateboard', 'roller skates', 'ice skates', 'skis', 'snowboard', 'sled',
  // clothing
  'hat', 'cap', 'crown', 'helmet', 'beanie', 'top hat', 'scarf', 'gloves', 'mittens', 'coat', 'jacket',
  'raincoat', 'sweater', 'hoodie', 'shirt', 't-shirt', 'tie', 'bow tie', 'dress', 'skirt', 'pants', 'jeans',
  'shorts', 'belt', 'socks', 'shoes', 'boots', 'sneakers', 'sandals', 'high heels', 'slippers', 'pajamas',
  'swimsuit', 'bikini', 'uniform', 'suit', 'wedding dress', 'tuxedo', 'cape', 'mask', 'wig', 'earrings',
  'necklace', 'ring', 'bracelet', 'watch', 'purse', 'diaper', 'bib', 'overalls', 'vest', 'kimono', 'poncho',
  // body & people
  'eye', 'eyebrow', 'eyelash', 'nose', 'mouth', 'lips', 'teeth', 'tongue', 'ear', 'hair', 'beard', 'mustache',
  'face', 'head', 'neck', 'shoulder', 'arm', 'elbow', 'hand', 'finger', 'thumb', 'fingernail', 'leg', 'knee',
  'foot', 'toe', 'heart', 'brain', 'skeleton', 'skull', 'bone', 'muscle', 'baby', 'boy', 'girl', 'man',
  'woman', 'grandma', 'grandpa', 'family', 'twins', 'king', 'queen', 'prince', 'princess', 'knight', 'wizard',
  'witch', 'ghost', 'zombie', 'vampire', 'mummy', 'skeleton key', 'pirate', 'ninja', 'cowboy', 'astronaut',
  'alien', 'superhero', 'clown', 'magician', 'chef', 'doctor', 'nurse', 'dentist', 'teacher', 'student',
  'police officer', 'firefighter', 'soldier', 'farmer', 'fisherman', 'lumberjack', 'mailman', 'pilot',
  'sailor', 'scientist', 'artist', 'photographer', 'musician', 'dancer', 'ballerina', 'cheerleader',
  'referee', 'lifeguard', 'judge', 'detective', 'spy', 'thief', 'robber', 'angel', 'devil', 'fairy', 'elf',
  'giant', 'dwarf', 'troll', 'goblin', 'genie', 'santa claus', 'snowman', 'scarecrow', 'mermaid tail',
  // nature & weather
  'sun', 'moon', 'star', 'cloud', 'rain', 'rainbow', 'snow', 'snowflake', 'lightning', 'thunderstorm',
  'tornado', 'hurricane', 'wind', 'fog', 'ice', 'icicle', 'fire', 'smoke', 'volcano', 'earthquake',
  'mountain', 'hill', 'valley', 'cliff', 'cave', 'canyon', 'desert', 'oasis', 'island', 'beach', 'ocean',
  'wave', 'river', 'lake', 'pond', 'waterfall', 'swamp', 'forest', 'jungle', 'tree', 'palm tree',
  'pine tree', 'cactus', 'bush', 'grass', 'flower', 'rose', 'tulip', 'sunflower', 'daisy', 'dandelion',
  'lily', 'leaf', 'branch', 'root', 'log', 'stump', 'acorn', 'pinecone', 'seed', 'sprout', 'vine', 'moss',
  'rock', 'stone', 'pebble', 'boulder', 'sand', 'mud', 'puddle', 'dirt', 'diamond', 'gem', 'crystal', 'gold',
  'pearl', 'shell', 'coral', 'seaweed', 'feather', 'egg nest', 'planet', 'earth', 'saturn', 'comet',
  'meteor', 'galaxy', 'black hole', 'eclipse', 'sunrise', 'sunset', 'north pole', 'glacier', 'iceberg',
  // places & buildings
  'house', 'apartment', 'castle', 'palace', 'tower', 'lighthouse', 'windmill', 'barn', 'farm', 'garden',
  'greenhouse', 'school', 'hospital', 'church', 'temple', 'mosque', 'pyramid', 'sphinx', 'igloo', 'cabin',
  'hut', 'skyscraper', 'bridge', 'tunnel', 'road', 'highway', 'crosswalk', 'traffic light', 'stop sign',
  'street lamp', 'fire hydrant', 'mailbox', 'bench', 'fountain', 'statue', 'park', 'playground', 'zoo',
  'circus', 'carnival', 'ferris wheel', 'roller coaster', 'carousel', 'stadium', 'gym', 'swimming pool',
  'library', 'museum', 'theater', 'cinema', 'restaurant', 'cafe', 'bakery', 'supermarket', 'shopping cart',
  'mall', 'bank', 'post office', 'police station', 'fire station', 'gas station', 'garage', 'factory',
  'office', 'prison', 'airport', 'train station', 'harbor', 'dock', 'bus stop', 'parking lot', 'elevator',
  'escalator', 'balcony', 'roof', 'attic', 'basement', 'fence', 'gate', 'wall', 'brick', 'well', 'graveyard',
  'tombstone', 'haunted house', 'maze', 'dungeon', 'throne', 'ruins', 'colosseum', 'eiffel tower',
  'statue of liberty', 'big ben', 'great wall', 'leaning tower', 'taj mahal', 'golden gate bridge',
  // vehicles
  'car', 'race car', 'taxi', 'police car', 'ambulance', 'fire truck', 'truck', 'pickup truck', 'van',
  'bus', 'school bus', 'train', 'subway', 'tram', 'bicycle', 'tricycle', 'unicycle', 'motorcycle',
  'scooter', 'skateboard ramp', 'wheel', 'tire', 'steering wheel', 'airplane', 'jet', 'helicopter',
  'hot air balloon', 'blimp', 'parachute', 'hang glider', 'rocket', 'space shuttle', 'satellite', 'ufo',
  'boat', 'sailboat', 'canoe', 'kayak', 'raft', 'cruise ship', 'pirate ship', 'submarine', 'yacht',
  'ferry', 'tractor', 'bulldozer', 'crane', 'excavator', 'cement mixer', 'forklift', 'tank', 'jeep',
  'limousine', 'golf cart', 'wagon', 'carriage', 'chariot', 'sleigh', 'snowmobile', 'jet ski', 'tow truck',
  'garbage truck', 'ice cream truck', 'monster truck', 'rickshaw', 'gondola', 'cable car', 'zeppelin',
  // sports & games
  'soccer ball', 'football', 'basketball', 'baseball', 'baseball bat', 'tennis ball', 'tennis racket',
  'golf ball', 'golf club', 'bowling ball', 'bowling pin', 'volleyball', 'hockey stick', 'puck', 'goal',
  'basketball hoop', 'trampoline', 'treadmill', 'dumbbell', 'barbell', 'yoga mat', 'boxing gloves',
  'punching bag', 'karate', 'wrestling', 'sumo', 'fencing', 'archery', 'bow and arrow', 'target', 'dart',
  'dartboard', 'billiards', 'ping pong', 'badminton', 'cricket', 'rugby', 'surfing', 'skiing', 'skating',
  'diving', 'swimming', 'running', 'marathon', 'cycling', 'horse riding', 'rowing', 'sailing', 'climbing',
  'hiking', 'fishing', 'camping', 'chess piece', 'video game', 'joystick', 'controller', 'arcade',
  'pinball', 'slot machine', 'bingo', 'poker', 'jigsaw puzzle', 'rubik cube', 'spinning top', 'kite flying',
  // music & art
  'guitar', 'electric guitar', 'bass guitar', 'violin', 'cello', 'piano', 'keyboard piano', 'drum',
  'drum set', 'trumpet', 'trombone', 'saxophone', 'flute', 'clarinet', 'harp', 'harmonica', 'accordion',
  'banjo', 'ukulele', 'tambourine', 'maracas', 'xylophone', 'triangle', 'bagpipes', 'tuba', 'bell',
  'music note', 'microphone stand', 'record player', 'cd', 'cassette', 'concert', 'orchestra', 'conductor',
  'opera', 'ballet', 'painting', 'sculpture', 'mosaic', 'origami', 'pottery', 'graffiti', 'cartoon',
  // tools & tech
  'hammer', 'nail', 'screw', 'screwdriver', 'wrench', 'saw', 'chainsaw', 'axe', 'drill', 'shovel', 'rake',
  'hoe', 'pitchfork', 'wheelbarrow', 'lawn mower', 'hose', 'watering can', 'sprinkler', 'toolbox',
  'measuring tape', 'level', 'pliers', 'anvil', 'blowtorch', 'crowbar', 'pickaxe', 'sickle', 'scythe',
  'magnet', 'gear', 'spring', 'chain', 'rope', 'knot', 'pulley', 'lever', 'wheelbarrow wheel', 'antenna',
  'satellite dish', 'solar panel', 'wind turbine', 'power line', 'circuit', 'chip', 'usb stick', 'hard drive',
  'floppy disk', 'cable', 'router', 'drone', '3d printer', 'virtual reality', 'calculator', 'abacus',
  'typewriter', 'projector', 'walkie talkie', 'pager', 'gramophone', 'hourglass', 'sundial', 'stopwatch',
  // concepts & actions (drawable)
  'sleeping', 'dreaming', 'crying', 'laughing', 'sneezing', 'yawning', 'hiccup', 'whistling', 'singing',
  'dancing', 'jumping', 'falling', 'flying', 'swimming pool party', 'reading', 'writing', 'drawing',
  'painting a wall', 'cooking', 'eating', 'drinking', 'shopping', 'driving', 'texting', 'selfie', 'kiss',
  'hug', 'high five', 'handshake', 'thumbs up', 'wave hello', 'salute', 'bow down', 'push up', 'cartwheel',
  'headstand', 'tiptoe', 'sneaking', 'hide and seek', 'tag', 'tug of war', 'pillow fight', 'snowball fight',
  'food fight', 'birthday', 'wedding', 'graduation', 'halloween', 'christmas', 'easter', 'new year',
  'valentine', 'thanksgiving', 'fireworks', 'parade', 'picnic basket', 'vacation', 'traffic jam',
  'rush hour', 'bedtime', 'nightmare', 'daydream', 'love', 'anger', 'fear', 'surprise', 'boredom', 'idea',
  'time', 'gravity', 'echo', 'shadow', 'reflection', 'invisible', 'silence', 'noise', 'smell', 'taste',
  'heat', 'cold', 'wet', 'dry', 'heavy', 'light weight', 'fast', 'slow', 'tall', 'short', 'big', 'small',
  'old', 'young', 'rich', 'poor', 'happy', 'sad', 'angry', 'scared', 'tired', 'hungry', 'thirsty', 'sick',
  'dizzy', 'lost', 'late', 'stuck', 'broken', 'melting', 'frozen', 'exploding', 'glowing', 'floating',
  'sinking', 'spinning', 'bouncing', 'climbing a tree', 'walking the dog', 'brushing teeth', 'taking a bath',
  'making a bed', 'mowing the lawn', 'washing dishes', 'doing laundry', 'baking', 'knitting', 'juggling',
  'skipping', 'bowling', 'surfing the web', 'gaming', 'streaming', 'podcast', 'emoji', 'hashtag', 'wifi',
  'password', 'download', 'upload', 'spam', 'virus', 'bug', 'cloud storage', 'selfie stick', 'meme',
  // misc objects
  'treasure chest', 'treasure map', 'sword', 'shield', 'spear', 'axe throw', 'cannon', 'cannonball',
  'pistol', 'bullet', 'bomb', 'dynamite', 'grenade', 'arrow', 'quiver', 'armor', 'lance', 'flag', 'banner',
  'trophy cup', 'crown jewels', 'scepter', 'wand', 'crystal ball', 'potion', 'cauldron', 'spellbook',
  'broomstick', 'coffin', 'tombstone cross', 'candle holder', 'chandelier', 'vase', 'bouquet', 'wreath',
  'garland', 'ornament', 'stocking', 'christmas tree', 'reindeer sleigh', 'present', 'cracker', 'piñata',
  'cake pop', 'jack-o-lantern', 'spider web', 'bat cave', 'cobweb', 'full moon', 'wolf howl', 'footprint',
  'fingerprint', 'paw print', 'hoof', 'horn', 'antler', 'tusk', 'claw', 'fang', 'tail', 'wing', 'fin',
  'scale', 'shell spiral', 'cocoon', 'honeycomb', 'anthill', 'molehill', 'burrow', 'den', 'kennel', 'cage',
  'aquarium', 'birdhouse', 'bird feeder', 'scarecrow hat', 'hay bale', 'silo', 'plow', 'fence post',
  'mailbox flag', 'welcome mat', 'doormat', 'curtain', 'blinds', 'carpet', 'rug', 'tile', 'wallpaper',
  'ceiling fan', 'smoke detector', 'thermostat', 'light switch', 'outlet', 'extension cord', 'hinge',
  'doorknob', 'peephole', 'keyhole', 'padlock', 'handcuffs', 'whistle', 'megaphone', 'siren', 'badge',
  'passport', 'ticket', 'boarding pass', 'luggage tag', 'receipt', 'coupon', 'barcode', 'qr code',
  'price tag', 'cash register', 'vending machine', 'atm', 'credit card', 'check', 'contract', 'diploma',
  'certificate', 'report card', 'test', 'homework', 'blackboard', 'chalk', 'whiteboard', 'desk', 'locker',
  'bell tower', 'school bell', 'bus driver', 'crossing guard', 'playground slide', 'monkey bars',
  'tetherball', 'hopscotch', 'chalk drawing', 'bubble', 'bubble wand', 'soap bubble', 'balloon animal',
  'face paint', 'costume', 'puppet', 'marionette', 'ventriloquist', 'juggler', 'acrobat', 'tightrope',
  'trapeze', 'cannon man', 'lion tamer', 'ringmaster', 'elephant trunk', 'popcorn bucket', 'cotton swab',
  'cotton ball', 'tissue', 'lotion', 'perfume', 'lipstick', 'nail polish', 'makeup', 'mascara', 'tweezers',
  'nail clipper', 'bobby pin', 'hair tie', 'headband', 'barrette', 'ponytail', 'braid', 'mohawk', 'bald',
  'afro', 'bun', 'pigtails', 'sideburns', 'goatee', 'unibrow', 'freckles', 'dimples', 'wrinkles', 'scar',
  'tattoo', 'piercing', 'braces', 'retainer', 'dentures', 'hearing aid', 'eye patch', 'monocle',
  'contact lens', 'bandana', 'turban', 'veil', 'tiara', 'halo', 'horns', 'devil tail', 'angel wings',
];
